name: Feature Branch CI
run-name: ${{ github.actor }} is testing out continuous integration

on:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./MusicBased_IOT_Platform.sln

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: trufflesecurity/trufflehog@main
